apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-dn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdn
  template:
    metadata:
      labels:
        app: flaskdn
    spec:
      containers:
      - name: flask-container-dn
        image: torbthemagni/flask-actions-project
        # imagePullPolicy: "Always"
        ports:
        - containerPort: 5000

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-canary-dn
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: flaskdn
#       version: canary
#   template:
#     metadata:
#       labels:
#         app: flaskdn
#         version: canary
#     spec:
#       containers:
#       - name: flask-container-dn
#         image: torbthemagni/flask-actions-project:latest