apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-deployment-dn
  labels:
    app.kubernetes.io/name: flask-dn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-dn
  template:
    metadata:
      labels:
        app: flask-dn
    spec:
      containers:
      - name: flask-container-dn
        image: torbthemagni/flask-actions-project
        ports:
        - containerPort: 5000
