apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-dn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdn
  template:
    metadata:
      labels:
        app: flaskdn
    spec:
      containers:
      - name: flask-container-dn
        image: torbthemagni/flask-actions-project
        ports:
        - containerPort: 5000
      restartPolicy: Always