apiVersion: v1
kind: Service
metadata:
  name: flask-service-dn
spec:
  selector:
    app.kubernetes.io/name: flask-dn
  type: LoadBalancer
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 52375
    targetPort: flaskwebsvc-dn