apiVersion: v1
kind: Service
metadata:
  name: flask-service-dn
spec:
  selector:
    app: flaskdn
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
